# Generated by Django 5.2.10 on 2026-01-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RECEPTIONIST', 'Receptionist'), ('HOUSEKEEPING', 'Housekeeping'), ('BAR_STAFF', 'Bar Staff'), ('ACCOUNTANT', 'Accountant'), ('MANAGER', 'Manager'), ('STAKEHOLDER', 'Stakeholder'), ('ADMIN', 'Admin')], default='RECEPTIONIST', max_length=20),
        ),
    ]
