# Generated by Django 5.2.10 on 2026-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_new_staff_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
