# Generated by Django 5.2.10 on 2026-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemevent',
            name='event_category',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('PAYMENT', 'Payment'), ('ROOM', 'Room'), ('EXPENSE', 'Expense'), ('AUTH', 'Auth'), ('ADMIN', 'Admin'), ('SECURITY', 'Security'), ('SYSTEM', 'System'), ('INVENTORY', 'Inventory')], db_index=True, max_length=20),
        ),
    ]
