# Generated by Django 5.2.10 on 2026-01-15 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_systemevent_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Cash in drawer at start', max_digits=12)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Cash declared at end', max_digits=12, null=True)),
                ('system_cash_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Cash recorded by system during shift', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Handover notes or variance explanation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
