# Generated by Django 5.2.10 on 2026-01-15 06:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expense_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('SOLAR_INVERTER', 'Solar Inverter'), ('GENERATOR', 'Generator'), ('AC_UNIT', 'Air Conditioning'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('maintenance_date', models.DateField()),
                ('next_scheduled', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_logs',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_ref', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_name', models.CharField(blank=True, max_length=100)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_logged', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['status', '-expense_date'], name='expenses_status_8c3170_idx'), models.Index(fields=['category', '-expense_date'], name='expenses_categor_2cd1f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_ref', models.CharField(max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment Received'), ('REFUND', 'Refund Issued'), ('CORRECTION', 'Correction Entry'), ('VOID', 'Voided Transaction')], default='PAYMENT', max_length=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS'), ('PAYSTACK', 'Paystack (Online)'), ('SPLIT', 'Split Payment')], default='CASH', max_length=15)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending Verification'), ('AWAITING_TRANSFER', 'Awaiting Transfer Confirmation'), ('FAILED', 'Failed')], db_index=True, default='CONFIRMED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('split_details', models.JSONField(blank=True, help_text="E.g., {'cash': 10000, 'transfer': 5000}", null=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, help_text='POS terminal ID, Paystack reference, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bookings.booking')),
                ('original_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='finance.transaction')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_processed', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', '-created_at'], name='transaction_booking_ba74ac_idx'), models.Index(fields=['transaction_type', '-created_at'], name='transaction_transac_a32e0c_idx'), models.Index(fields=['status', '-created_at'], name='transaction_status_b84006_idx')],
            },
        ),
    ]
