# Generated by Django 5.2.10 on 2026-01-15 06:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_ref', models.CharField(db_index=True, max_length=12, unique=True)),
                ('stay_type', models.CharField(choices=[('SHORT_REST', 'Short Rest (2-4 hrs)'), ('OVERNIGHT', 'Overnight'), ('LODGE', 'Lodge (Multi-night)')], default='OVERNIGHT', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='PENDING', max_length=15)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('ONLINE', 'Online Booking'), ('PHONE', 'Phone Reservation'), ('CORPORATE', 'Corporate Account')], default='WALK_IN', max_length=15)),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('expected_checkout', models.DateTimeField()),
                ('actual_checkout', models.DateTimeField(blank=True, null=True)),
                ('num_nights', models.PositiveSmallIntegerField(default=1)),
                ('num_guests', models.PositiveSmallIntegerField(default=1)),
                ('room_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_reason', models.CharField(blank=True, max_length=200)),
                ('is_complimentary', models.BooleanField(default=False)),
                ('complimentary_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_checkout', models.DateTimeField()),
                ('new_checkout', models.DateTimeField()),
                ('additional_nights', models.PositiveSmallIntegerField(default=0)),
                ('additional_hours', models.PositiveSmallIntegerField(default=0)),
                ('additional_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_extensions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True, help_text='VIP status, preferences, etc.')),
                ('is_blocked', models.BooleanField(default=False, help_text='Block problematic guests')),
                ('total_stays', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('current_state', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('DIRTY', 'Dirty'), ('CLEANING', 'Being Cleaned'), ('MAINTENANCE', 'Under Maintenance')], db_index=True, default='AVAILABLE', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the room')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomStateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=15)),
                ('to_state', models.CharField(max_length=15)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'room_state_transitions',
                'ordering': ['-transitioned_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_rate_short_rest', models.DecimalField(decimal_places=2, help_text='Rate for 2-4 hour short rest', max_digits=10)),
                ('base_rate_overnight', models.DecimalField(decimal_places=2, help_text='Rate for overnight stay (checkout by 12 PM)', max_digits=10)),
                ('base_rate_lodge', models.DecimalField(blank=True, decimal_places=2, help_text='Weekly/extended stay rate (optional)', max_digits=10, null=True)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'room_types',
                'ordering': ['name'],
            },
        ),
    ]
