# Generated by Django 5.2.10 on 2026-01-15 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingextension',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingextension',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.guest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.room'),
        ),
        migrations.AddField(
            model_name='roomstatetransition',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='bookings.room'),
        ),
        migrations.AddField(
            model_name='roomstatetransition',
            name='transitioned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_transitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='bookings.roomtype'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in_date', 'status'], name='bookings_check_i_9ea1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'status'], name='bookings_room_id_e4aa25_idx'),
        ),
        migrations.AddIndex(
            model_name='roomstatetransition',
            index=models.Index(fields=['room', '-transitioned_at'], name='room_state__room_id_31b190_idx'),
        ),
        migrations.AddIndex(
            model_name='roomstatetransition',
            index=models.Index(fields=['to_state', 'transitioned_at'], name='room_state__to_stat_d4265c_idx'),
        ),
    ]
