# Generated by Django 5.2.10 on 2026-01-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_code',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
